include themes/kanso-ink.conf

font_family Lilex Nerd Font Mono
font_size 18.0

cursor_shape block

hide_window_decorations titlebar-only
macos_titlebar_color dark
macos_option_as_alt yes
confirm_os_window_close 0

# top right bottom left
window_padding_width 20 20 5 20
